# Read the Docs configuration file
# https://docs.readthedocs.io/en/stable/config-file/v2.html
version: 2

# OS and Python version
build:
  os: ubuntu-24.04
  tools:
    python: "3.11"

# Build Sphinx documentation from docs/ folder
sphinx:
  configuration: docs/conf.py

# Optional: install Python requirements for building docs
python:
  install:
    - requirements: docs/requirements.txt
